# Generated by Django 5.1.1 on 2024-09-18 19:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIngreso',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('horaIngreso', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Ingreso')),
                ('ingresoCalefaccion', models.BooleanField(verbose_name='Ingreso para calefaccion de cisterna')),
                ('remito', models.CharField(max_length=100, verbose_name='Remito')),
                ('ingresado', models.BooleanField(default=False, verbose_name='Ingresado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('conductor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.conductor')),
                ('empresaTransporte', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.transporte')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patenteChasis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.camion')),
                ('patenteSemi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.semi')),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.producto')),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal')),
            ],
            options={
                'verbose_name': 'historical Ingreso',
                'verbose_name_plural': 'historical Ingresos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('horaIngreso', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Ingreso')),
                ('ingresoCalefaccion', models.BooleanField(verbose_name='Ingreso para calefaccion de cisterna')),
                ('remito', models.CharField(max_length=100, verbose_name='Remito')),
                ('ingresado', models.BooleanField(default=False, verbose_name='Ingresado')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.conductor')),
                ('empresaTransporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.transporte')),
                ('patenteChasis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.camion')),
                ('patenteSemi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.semi')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.producto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.personal')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
    ]
