# Generated by Django 5.1.1 on 2026-07-14 13:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hdr', '0001_initial'),
        ('personal', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Salida')),
                ('verificacion', models.BooleanField(default=False, verbose_name='verificacion de vehiculo/carga')),
                ('salida_autorizada', models.BooleanField(default=False, verbose_name='Salida Autorizada')),
                ('hdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hdr.hdr')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.personal')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_control', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Control')),
                ('casco', models.BooleanField(default=False, verbose_name='casco')),
                ('mascara', models.BooleanField(default=False, verbose_name='mascara')),
                ('antiparras', models.BooleanField(default=False, verbose_name='antiparras PVC')),
                ('botines', models.BooleanField(default=False, verbose_name='botines')),
                ('pantalon_camisa', models.BooleanField(default=False, verbose_name='pantalon/camisa/mameluco anti-ácido')),
                ('matafuego', models.BooleanField(default=False, verbose_name='matafuego')),
                ('arrestallamas', models.BooleanField(verbose_name='arrestallamas')),
                ('carteleria', models.BooleanField(default=False, verbose_name='carteleria')),
                ('hdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hdr.hdr')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.personal')),
            ],
            options={
                'verbose_name': 'EPP',
                'verbose_name_plural': 'EPP',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEgreso',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha_salida', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Salida')),
                ('verificacion', models.BooleanField(default=False, verbose_name='verificacion de vehiculo/carga')),
                ('salida_autorizada', models.BooleanField(default=False, verbose_name='Salida Autorizada')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hdr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hdr.hdr')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal')),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelos Base',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIngreso',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('hora_ingreso', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Ingreso')),
                ('ingreso_calefaccion', models.BooleanField(verbose_name='Ingreso para calefaccion de cisterna')),
                ('remito', models.CharField(db_index=True, max_length=100, verbose_name='Remito')),
                ('ingresado', models.BooleanField(default=False, verbose_name='Ingresado')),
                ('laborable', models.BooleanField(default=True, verbose_name='Dia Laborable')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('conductor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.conductor')),
                ('empresa_transporte', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.transporte')),
                ('hdr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hdr.hdr')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patente_chasis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.camion')),
                ('patente_semi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.semi')),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.producto')),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal')),
            ],
            options={
                'verbose_name': 'historical Ingreso',
                'verbose_name_plural': 'historical Ingresos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('hora_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Ingreso')),
                ('ingreso_calefaccion', models.BooleanField(verbose_name='Ingreso para calefaccion de cisterna')),
                ('remito', models.CharField(max_length=100, unique=True, verbose_name='Remito')),
                ('ingresado', models.BooleanField(default=False, verbose_name='Ingresado')),
                ('laborable', models.BooleanField(default=True, verbose_name='Dia Laborable')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.conductor')),
                ('empresa_transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.transporte')),
                ('hdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hdr.hdr')),
                ('patente_chasis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.camion')),
                ('patente_semi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.semi')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.producto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.personal')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
    ]
