# Generated by Django 5.1.1 on 2024-10-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteria2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalingreso',
            old_name='empresaTransporte',
            new_name='empresa_transporte',
        ),
        migrations.RenameField(
            model_name='historicalingreso',
            old_name='horaIngreso',
            new_name='hora_ingreso',
        ),
        migrations.RenameField(
            model_name='historicalingreso',
            old_name='ingresoCalefaccion',
            new_name='ingreso_calefaccion',
        ),
        migrations.RenameField(
            model_name='historicalingreso',
            old_name='patenteChasis',
            new_name='patente_chasis',
        ),
        migrations.RenameField(
            model_name='historicalingreso',
            old_name='patenteSemi',
            new_name='patente_semi',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='empresaTransporte',
            new_name='empresa_transporte',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='horaIngreso',
            new_name='hora_ingreso',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='ingresoCalefaccion',
            new_name='ingreso_calefaccion',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='patenteChasis',
            new_name='patente_chasis',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='patenteSemi',
            new_name='patente_semi',
        ),
    ]
