# Generated by Django 5.1.1 on 2026-07-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteria2', '0002_egreso_historicalegreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='fecha_salida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='historicalegreso',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Salida'),
        ),
    ]
