# Generated by Django 5.1.1 on 2024-10-31 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0001_initial'),
        ('porteria2', '0002_rename_empresatransporte_historicalingreso_empresa_transporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingreso',
            name='id_hdr',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hdr.hdr'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='id_hdr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hdr.hdr'),
            preserve_default=False,
        ),
    ]
