# Generated by Django 5.1.1 on 2025-11-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteria2', '0002_egreso_historicalegreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingreso',
            name='laborable',
            field=models.BooleanField(default=True, verbose_name='Dia Laborable'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='laborable',
            field=models.BooleanField(default=True, verbose_name='Dia Laborable'),
        ),
    ]
