# Generated by Django 5.1.1 on 2025-11-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteria2', '0003_rename_laboral_historicalingreso_laborable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalingreso',
            name='laboral',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='laboral',
        ),
    ]
