# Generated by Django 5.1.1 on 2024-11-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteria2', '0003_historicalingreso_id_hdr_ingreso_id_hdr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalingreso',
            old_name='id_hdr',
            new_name='hdr',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='id_hdr',
            new_name='hdr',
        ),
    ]
