# Generated by Django 5.1.1 on 2025-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteria2', '0004_remove_historicalingreso_laboral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='fecha_salida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='historicalegreso',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='historicalingreso',
            name='remito',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Remito'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='remito',
            field=models.CharField(max_length=100, unique=True, verbose_name='Remito'),
        ),
    ]
