# Generated by Django 5.1.1 on 2024-11-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_personal_is_deleted_alter_personal_legajo_and_more'),
        ('porteria2', '0004_rename_id_hdr_historicalingreso_hdr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casco', models.BooleanField(default=False, verbose_name='casco')),
                ('mascara', models.BooleanField(default=False, verbose_name='mascara')),
                ('antiparras', models.BooleanField(default=False, verbose_name='antiparras PVC')),
                ('botines', models.BooleanField(default=False, verbose_name='botines')),
                ('pantalon_camisa', models.BooleanField(default=False, verbose_name='pantalon/camisa/mameluco anti-ácido')),
                ('matafuego', models.BooleanField(default=False, verbose_name='matafuego')),
                ('arrestallamas', models.BooleanField(verbose_name='arrestallamas')),
                ('carteleria', models.BooleanField(default=False, verbose_name='carteleria')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.personal')),
            ],
            options={
                'verbose_name': 'EPP',
                'verbose_name_plural': 'EPP',
            },
        ),
    ]
