# Generated by Django 5.1.1 on 2024-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteria2', '0005_epp'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingreso',
            name='laboral',
            field=models.BooleanField(default=True, verbose_name='Dia Laborable'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='laboral',
            field=models.BooleanField(default=True, verbose_name='Dia Laborable'),
        ),
    ]
