# Generated by Django 5.1.1 on 2026-01-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0001_initial'),
        ('porteria2', '0005_alter_egreso_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epp',
            name='hdr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hdr.hdr'),
            preserve_default=False,
        ),
    ]
