# Generated by Django 5.1.1 on 2026-01-08 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteria2', '0006_epp_hdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='epp',
            name='fecha_control',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Control'),
            preserve_default=False,
        ),
    ]
