# Generated by Django 5.1.1 on 2024-12-10 13:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hdr', '0003_hdr_observacion_historicalhdr_observacion'),
        ('personal', '0004_alter_personal_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInspeccion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('hora_extraccion', models.DateTimeField(verbose_name='Hora Extracción')),
                ('certificado', models.BooleanField(verbose_name='Ingresa con certificado')),
                ('requisitos', models.BooleanField(verbose_name='Cumple requisitos')),
                ('observacion', models.TextField(blank=True, max_length=200, null=True, verbose_name='observacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hdr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hdr.hdr', verbose_name='HDR')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal')),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelos Base',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('hora_extraccion', models.DateTimeField(verbose_name='Hora Extracción')),
                ('certificado', models.BooleanField(verbose_name='Ingresa con certificado')),
                ('requisitos', models.BooleanField(verbose_name='Cumple requisitos')),
                ('observacion', models.TextField(blank=True, max_length=200, null=True, verbose_name='observacion')),
                ('hdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hdr.hdr', verbose_name='HDR')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.personal')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
    ]
