# Generated by Django 5.1.1 on 2026-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinspeccion',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
    ]
