# Generated by Django 5.1.1 on 2026-07-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinspeccion',
            name='descargar',
            field=models.BooleanField(default=True, verbose_name='Autorizado a descargar'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='descargar',
            field=models.BooleanField(default=True, verbose_name='Autorizado a descargar'),
        ),
    ]
