# Generated by Django 5.1.1 on 2026-01-09 14:20

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinspeccion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 9, 14, 20, 29, 939145), editable=False, verbose_name='Fecha de Inspeccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Inspeccion'),
            preserve_default=False,
        ),
    ]
