# Generated by Django 5.1.1 on 2026-07-15 14:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hdr', '0001_initial'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPamoPsul',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('hora_ingreso', models.TimeField(verbose_name='Hora de Ingreso')),
                ('presion_ingreso', models.FloatField(null=True, verbose_name='Presión Ingreso')),
                ('temperatura_ingreso', models.FloatField(null=True, verbose_name='Temperatura Ingreso')),
                ('presion_salida', models.FloatField(null=True, verbose_name='Presión Salida')),
                ('temperatura_salida', models.FloatField(null=True, verbose_name='Temperatura Salida')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hdr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hdr.hdr', verbose_name='HDR')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'historical pamo psul',
                'verbose_name_plural': 'historical pamo psuls',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PamoPsul',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('hora_ingreso', models.TimeField(verbose_name='Hora de Ingreso')),
                ('presion_ingreso', models.FloatField(null=True, verbose_name='Presión Ingreso')),
                ('temperatura_ingreso', models.FloatField(null=True, verbose_name='Temperatura Ingreso')),
                ('presion_salida', models.FloatField(null=True, verbose_name='Presión Salida')),
                ('temperatura_salida', models.FloatField(null=True, verbose_name='Temperatura Salida')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('hdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hdr.hdr', verbose_name='HDR')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.personal', verbose_name='Responsable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
