# Generated by Django 5.1.1 on 2026-03-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vigencia', models.DateTimeField(verbose_name='Fecha de Vigencia')),
                ('version', models.CharField(max_length=4, verbose_name='Versión')),
                ('registro', models.CharField(max_length=100, verbose_name='Registro')),
            ],
        ),
    ]
