# Generated by Django 5.1.1 on 2026-07-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('Porteria 2', 'Porteria 2'), ('Inspeccion Quimica', 'Inspeccion Quimica'), ('Almacen PQ', 'Almacen PQ'), ('SHYMA', 'SHYMA'), ('PAMO', 'PAMO'), ('PSUL', 'PSUL')], max_length=100)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('legajo', models.CharField(max_length=5, unique=True, verbose_name='Nº Legajo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
        ),
    ]
