# Generated by Django 5.1.1 on 2026-09-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='sector',
            field=models.CharField(choices=[('Porteria 2', 'Porteria 2'), ('Inspeccion Quimica', 'Inspeccion Quimica'), ('Almacen PQ', 'Almacen PQ'), ('SHYMA', 'SHYMA'), ('PAMO', 'PAMO'), ('PSUL', 'PSUL'), ('Gestion de Acceso', 'Gestion de Acceso')], max_length=100),
        ),
    ]
