# Generated by Django 5.1.1 on 2026-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='sector',
            field=models.CharField(choices=[('Porteria 2', 'Porteria 2'), ('Inspeccion Quimica', 'Inspeccion Quimica'), ('Balanza', 'Balanza'), ('PAMO', 'PAMO'), ('PSUL', 'PSUL')], max_length=100),
        ),
    ]
