# Generated by Django 5.1.1 on 2024-10-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='legajo',
            field=models.CharField(max_length=5, unique=True, verbose_name='Nº Legajo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sector',
            field=models.CharField(choices=[('Porteria 2', 'Porteria 2')], max_length=100),
        ),
    ]
