# Generated by Django 5.1.1 on 2024-11-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_personal_is_deleted_alter_personal_legajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='sector',
            field=models.CharField(choices=[('Porteria 2', 'Porteria 2'), ('Inspeccion Quimica', 'Inspeccion Quimica')], max_length=100),
        ),
    ]
