# Generated by Django 5.1.1 on 2024-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_personal_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='sector',
            field=models.CharField(choices=[('Porteria 2', 'Porteria 2'), ('Inspeccion Quimica', 'Inspeccion Quimica'), ('Almacen PQ', 'Almacen PQ')], max_length=100),
        ),
    ]
