# Generated by Django 5.1.1 on 2026-07-29 14:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hdr', '0001_initial'),
        ('personal', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('hora_ingreso', models.DateTimeField(verbose_name='Hora de Ingreso')),
                ('remito', models.CharField(default='', max_length=100, verbose_name='Remito')),
                ('peso_origen', models.IntegerField(default=0, verbose_name='Peso de Origen')),
                ('observaciones', models.TextField(default='DOD según el IN 11-IQ-07', max_length=100)),
                ('fecha_salida', models.DateTimeField(null=True, verbose_name='Fecha de Salida')),
                ('peso_fmrt', models.IntegerField(default=0, null=True, verbose_name='Peso en FMRT')),
                ('peso_vacio', models.IntegerField(default=0, null=True, verbose_name='Peso vacio')),
                ('peso_taquilla', models.IntegerField(default=0, verbose_name='Peso taquilla')),
                ('peso_bolsa_tarima', models.IntegerField(default=0, verbose_name='Peso bolsa/tarima')),
                ('peso_neto', models.IntegerField(default=0, null=True, verbose_name='Peso neto')),
                ('hdr', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hdr.hdr', verbose_name='HDR')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor', verbose_name='Proveedor')),
                ('responsable_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsable_entrada', to='personal.personal', verbose_name='Responsable Entrada')),
                ('responsable_salida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsable_salida', to='personal.personal', verbose_name='Responsable Salida')),
            ],
            options={
                'verbose_name': 'Balanza',
                'verbose_name_plural': 'Balanza',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBalanza',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('hora_ingreso', models.DateTimeField(verbose_name='Hora de Ingreso')),
                ('remito', models.CharField(default='', max_length=100, verbose_name='Remito')),
                ('peso_origen', models.IntegerField(default=0, verbose_name='Peso de Origen')),
                ('observaciones', models.TextField(default='DOD según el IN 11-IQ-07', max_length=100)),
                ('fecha_salida', models.DateTimeField(null=True, verbose_name='Fecha de Salida')),
                ('peso_fmrt', models.IntegerField(default=0, null=True, verbose_name='Peso en FMRT')),
                ('peso_vacio', models.IntegerField(default=0, null=True, verbose_name='Peso vacio')),
                ('peso_taquilla', models.IntegerField(default=0, verbose_name='Peso taquilla')),
                ('peso_bolsa_tarima', models.IntegerField(default=0, verbose_name='Peso bolsa/tarima')),
                ('peso_neto', models.IntegerField(default=0, null=True, verbose_name='Peso neto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hdr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hdr.hdr', verbose_name='HDR')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('responsable_entrada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal', verbose_name='Responsable Entrada')),
                ('responsable_salida', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal', verbose_name='Responsable Salida')),
            ],
            options={
                'verbose_name': 'historical Balanza',
                'verbose_name_plural': 'historical Balanza',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
