# Generated by Django 5.1.1 on 2024-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanza',
            name='remito',
            field=models.CharField(default='', max_length=100, verbose_name='Remito'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='remito',
            field=models.CharField(default='', max_length=100, verbose_name='Remito'),
        ),
    ]
