# Generated by Django 5.1.1 on 2026-07-16 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0001_initial'),
        ('hdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanza',
            name='hdr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hdr.hdr', verbose_name='HDR'),
        ),
    ]
