# Generated by Django 5.1.1 on 2025-01-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanza',
            name='responsable_salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsable_salida', to='personal.personal', verbose_name='Responsable Salida'),
        ),
        migrations.AddField(
            model_name='historicalbalanza',
            name='responsable_salida',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal', verbose_name='Responsable Salida'),
        ),
    ]
