# Generated by Django 5.1.1 on 2025-01-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0002_balanza_responsable_salida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balanza',
            old_name='responsable_salida',
            new_name='responsableSalida',
        ),
        migrations.RenameField(
            model_name='historicalbalanza',
            old_name='responsable_salida',
            new_name='responsableSalida',
        ),
    ]
