# Generated by Django 5.1.1 on 2024-12-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0002_alter_balanza_remito_alter_historicalbalanza_remito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanza',
            name='hora_ingreso',
            field=models.DateTimeField(verbose_name='Hora de Ingreso'),
        ),
        migrations.AlterField(
            model_name='balanza',
            name='hora_salida',
            field=models.DateTimeField(null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='hora_ingreso',
            field=models.DateTimeField(verbose_name='Hora de Ingreso'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='hora_salida',
            field=models.DateTimeField(null=True, verbose_name='Hora de salida'),
        ),
    ]
