# Generated by Django 5.1.1 on 2024-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0003_alter_balanza_hora_ingreso_alter_balanza_hora_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanza',
            name='peso_fmrt',
            field=models.IntegerField(null=True, verbose_name='Peso en FMRT'),
        ),
        migrations.AlterField(
            model_name='balanza',
            name='peso_neto',
            field=models.IntegerField(null=True, verbose_name='Peso neto'),
        ),
        migrations.AlterField(
            model_name='balanza',
            name='peso_taquilla',
            field=models.IntegerField(null=True, verbose_name='Peso taquilla'),
        ),
        migrations.AlterField(
            model_name='balanza',
            name='peso_vacio',
            field=models.IntegerField(null=True, verbose_name='peso vacio'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='peso_fmrt',
            field=models.IntegerField(null=True, verbose_name='Peso en FMRT'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='peso_neto',
            field=models.IntegerField(null=True, verbose_name='Peso neto'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='peso_taquilla',
            field=models.IntegerField(null=True, verbose_name='Peso taquilla'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='peso_vacio',
            field=models.IntegerField(null=True, verbose_name='peso vacio'),
        ),
    ]
