# Generated by Django 5.1.1 on 2025-01-07 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0003_rename_responsable_salida_balanza_responsablesalida_and_more'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balanza',
            old_name='responsableSalida',
            new_name='responsable_salida',
        ),
        migrations.RenameField(
            model_name='historicalbalanza',
            old_name='responsableSalida',
            new_name='responsable_salida',
        ),
        migrations.RemoveField(
            model_name='balanza',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='historicalbalanza',
            name='responsable',
        ),
        migrations.AddField(
            model_name='balanza',
            name='responsable_entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='responsable_entrada', to='personal.personal', verbose_name='Responsable Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbalanza',
            name='responsable_entrada',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal', verbose_name='Responsable Entrada'),
        ),
    ]
