# Generated by Django 5.1.1 on 2025-01-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0005_alter_balanza_responsable_salida'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanza',
            name='responsable_salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsable_salida', to='personal.personal', verbose_name='Responsable Salida'),
        ),
    ]
