# Generated by Django 5.1.1 on 2025-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0006_alter_balanza_responsable_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanza',
            name='fecha_salida',
            field=models.DateField(null=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AddField(
            model_name='historicalbalanza',
            name='fecha_salida',
            field=models.DateField(null=True, verbose_name='Fecha de Salida'),
        ),
    ]
