# Generated by Django 5.1.1 on 2025-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0007_balanza_fecha_salida_historicalbalanza_fecha_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanza',
            name='hora_salida',
        ),
        migrations.RemoveField(
            model_name='historicalbalanza',
            name='hora_salida',
        ),
        migrations.AlterField(
            model_name='balanza',
            name='fecha_salida',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='balanza',
            name='peso_bolsa_tarima',
            field=models.IntegerField(default=0, verbose_name='Peso bolsa/tarima'),
        ),
        migrations.AlterField(
            model_name='balanza',
            name='peso_fmrt',
            field=models.IntegerField(default=0, null=True, verbose_name='Peso en FMRT'),
        ),
        migrations.AlterField(
            model_name='balanza',
            name='peso_neto',
            field=models.IntegerField(default=0, null=True, verbose_name='Peso neto'),
        ),
        migrations.AlterField(
            model_name='balanza',
            name='peso_taquilla',
            field=models.IntegerField(default=0, verbose_name='Peso taquilla'),
        ),
        migrations.AlterField(
            model_name='balanza',
            name='peso_vacio',
            field=models.IntegerField(default=0, null=True, verbose_name='Peso vacio'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='fecha_salida',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='peso_bolsa_tarima',
            field=models.IntegerField(default=0, verbose_name='Peso bolsa/tarima'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='peso_fmrt',
            field=models.IntegerField(default=0, null=True, verbose_name='Peso en FMRT'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='peso_neto',
            field=models.IntegerField(default=0, null=True, verbose_name='Peso neto'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='peso_taquilla',
            field=models.IntegerField(default=0, verbose_name='Peso taquilla'),
        ),
        migrations.AlterField(
            model_name='historicalbalanza',
            name='peso_vacio',
            field=models.IntegerField(default=0, null=True, verbose_name='Peso vacio'),
        ),
    ]
