# Generated by Django 5.1.1 on 2025-11-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['producto'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='historicalproducto',
            old_name='nombre',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='producto',
        ),
    ]
