# Generated by Django 5.1.1 on 2024-11-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='producto',
            field=models.CharField(choices=[('Azufre', 'Azufre Liquido'), ('Azufre solido', 'Azufre solido a granel'), ('Amoniaco', 'Amoniaco')], max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(choices=[('Azufre', 'Azufre Liquido'), ('Azufre solido', 'Azufre solido a granel'), ('Amoniaco', 'Amoniaco')], max_length=100),
        ),
    ]
