# Generated by Django 5.1.1 on 2024-11-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_proveedor_remove_proveedores_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='nombre',
            field=models.TextField(default='', max_length=100, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='nombre',
            field=models.TextField(max_length=50, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(default='', max_length=100, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.TextField(max_length=50, verbose_name='Proveedor'),
        ),
    ]
