# Generated by Django 5.1.1 on 2026-05-29 12:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Empresa de Transporte',
                'verbose_name_plural': 'Empresas de Transporte',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransporte',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre', models.CharField(db_index=True, max_length=50, verbose_name='Transporte')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Empresa de Transporte',
                'verbose_name_plural': 'historical Empresas de Transporte',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Semi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('vencimiento_seguro', models.DateField(verbose_name='Vencimiento Seguro Semi')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.transporte', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Semi',
                'verbose_name_plural': 'Semis',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSemi',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('patente', models.CharField(db_index=True, max_length=10, verbose_name='Patente')),
                ('vencimiento_seguro', models.DateField(verbose_name='Vencimiento Seguro Semi')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transporte', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.transporte', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'historical Semi',
                'verbose_name_plural': 'historical Semis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalConductor',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre', models.CharField(db_index=True, max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('dni', models.CharField(db_index=True, max_length=15, verbose_name='DNI')),
                ('vencimiento_carnet', models.DateField(verbose_name='Vencimiento Carnet')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transporte', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.transporte', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'historical Conductor',
                'verbose_name_plural': 'historical Conductores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCamion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('marca', models.CharField(choices=[('Mercedes-Benz', 'Mercedes-Benz'), ('Volvo', 'Volvo'), ('Scania', 'Scania'), ('Iveco', 'Iveco'), ('Ford', 'Ford'), ('MAN', 'MAN'), ('Hino', 'Hino'), ('Isuzu', 'Isuzu'), ('Chevrolet', 'Chevrolet'), ('Kenworth', 'Kenworth')], max_length=30, verbose_name='Marca')),
                ('patente', models.CharField(db_index=True, max_length=10, verbose_name='Patente')),
                ('vencimiento_seguro', models.DateField(verbose_name='Vencimiento Seguro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transporte', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transporte.transporte', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'historical Camión',
                'verbose_name_plural': 'historical Camiones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('vencimiento_carnet', models.DateField(verbose_name='Vencimiento Carnet')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.transporte', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('marca', models.CharField(choices=[('Mercedes-Benz', 'Mercedes-Benz'), ('Volvo', 'Volvo'), ('Scania', 'Scania'), ('Iveco', 'Iveco'), ('Ford', 'Ford'), ('MAN', 'MAN'), ('Hino', 'Hino'), ('Isuzu', 'Isuzu'), ('Chevrolet', 'Chevrolet'), ('Kenworth', 'Kenworth')], max_length=30, verbose_name='Marca')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('vencimiento_seguro', models.DateField(verbose_name='Vencimiento Seguro')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.transporte', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
            },
        ),
    ]
