# Generated by Django 5.1.1 on 2024-09-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsemi',
            old_name='vencimientoSeguro',
            new_name='vencimiento_seguro',
        ),
        migrations.RenameField(
            model_name='semi',
            old_name='vencimientoSeguro',
            new_name='vencimiento_seguro',
        ),
        migrations.AlterField(
            model_name='camion',
            name='patente',
            field=models.CharField(max_length=10, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='historicalcamion',
            name='patente',
            field=models.CharField(max_length=10, verbose_name='Patente'),
        ),
    ]
