# Generated by Django 5.1.1 on 2024-09-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_rename_vencimientoseguro_historicalsemi_vencimiento_seguro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsemi',
            name='patente',
            field=models.CharField(max_length=10, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='semi',
            name='patente',
            field=models.CharField(max_length=10, verbose_name='Patente'),
        ),
    ]
