# Generated by Django 5.1.1 on 2024-10-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_alter_historicalsemi_patente_alter_semi_patente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='vencimientoCarnet',
            new_name='vencimiento_carnet',
        ),
        migrations.RenameField(
            model_name='historicalconductor',
            old_name='vencimientoCarnet',
            new_name='vencimiento_carnet',
        ),
    ]
