# Generated by Django 5.1.1 on 2024-10-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_rename_vencimientocarnet_conductor_vencimiento_carnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='patente',
            field=models.CharField(max_length=10, unique=True, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalcamion',
            name='patente',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='historicalconductor',
            name='nombre',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalsemi',
            name='patente',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='semi',
            name='patente',
            field=models.CharField(max_length=10, unique=True, verbose_name='Patente'),
        ),
    ]
