# Generated by Django 5.1.1 on 2026-08-14 09:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HDR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Feha')),
                ('sector', models.CharField(choices=[('Porteria 2', 'Porteria 2'), ('Porteria 2 E', 'Porteria 2 E'), ('Almacen PQ', 'Almacen PQ'), ('Almacen PQ E', 'Almacen PQ E'), ('Inspeccion PQ', 'Inspeccion PQ'), ('PAMO', 'PAMO'), ('PSUL', 'PSUL')], default='Porteria 2', max_length=20, verbose_name='Sector')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Anulado', 'Anulado'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado')], default='Activo', max_length=20, verbose_name='Estado')),
                ('observacion', models.CharField(blank=True, default='', max_length=200, verbose_name='Observaciones')),
                ('rechazado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personal.personal', verbose_name='Rechazado por')),
            ],
            options={
                'verbose_name': 'HDR',
                'verbose_name_plural': 'HDR',
            },
        ),
        migrations.CreateModel(
            name='HistoricalHDR',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha', models.DateTimeField(blank=True, editable=False, verbose_name='Feha')),
                ('sector', models.CharField(choices=[('Porteria 2', 'Porteria 2'), ('Porteria 2 E', 'Porteria 2 E'), ('Almacen PQ', 'Almacen PQ'), ('Almacen PQ E', 'Almacen PQ E'), ('Inspeccion PQ', 'Inspeccion PQ'), ('PAMO', 'PAMO'), ('PSUL', 'PSUL')], default='Porteria 2', max_length=20, verbose_name='Sector')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Anulado', 'Anulado'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado')], default='Activo', max_length=20, verbose_name='Estado')),
                ('observacion', models.CharField(blank=True, default='', max_length=200, verbose_name='Observaciones')),
                ('rechazado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal', verbose_name='Rechazado por')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical HDR',
                'verbose_name_plural': 'historical HDR',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]