# Generated by Django 5.1.1 on 2026-08-13 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdr',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personal.personal', verbose_name='Rechazado por'),
        ),
        migrations.AddField(
            model_name='historicalhdr',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal', verbose_name='Rechazado por'),
        ),
    ]
