# Generated by Django 5.1.1 on 2026-08-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdr',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Anulado', 'Anulado'), ('Finalizado', 'Finalizado'), ('RechazoConfirmado', 'RechazoConfirmado'), ('Rechazado', 'Rechazado')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalhdr',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Anulado', 'Anulado'), ('Finalizado', 'Finalizado'), ('RechazoConfirmado', 'RechazoConfirmado'), ('Rechazado', 'Rechazado')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
    ]
