# Generated by Django 5.1.1 on 2024-11-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdr',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Anulado', 'Anulado'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='hdr',
            name='sector',
            field=models.CharField(choices=[('Porteria 2', 'Porteria 2'), ('Almacen PQ', 'Almacen PQ'), ('Inspeccion PQ', 'Inspeccion PQ'), ('PAMO/PSUL', 'PAMO/PSUL')], default='Porteria 2', max_length=20, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='historicalhdr',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Anulado', 'Anulado'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalhdr',
            name='sector',
            field=models.CharField(choices=[('Porteria 2', 'Porteria 2'), ('Almacen PQ', 'Almacen PQ'), ('Inspeccion PQ', 'Inspeccion PQ'), ('PAMO/PSUL', 'PAMO/PSUL')], default='Porteria 2', max_length=20, verbose_name='Sector'),
        ),
    ]
