# Generated by Django 5.1.1 on 2024-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0002_alter_hdr_estado_alter_hdr_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdr',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='historicalhdr',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Observaciones'),
        ),
    ]
